### ISSUE TITLE
[FEAT]: Sir I have a simple Question 

### ISSUE THREAD

**Issue by iamacat02** [C10udburst/MessengerEx#1]
### Description

Sir, I can see by installing your module that your module has automatically selected the messenger before enabling the module. My request to you is, how did you implement it?I have created a module but can't get this feature. I will credit you on all my projects if you tell me.

**Comment by C10udburst** [comment]
https://github.com/C10udburst/MessengerEx/blob/master/app/src/main/AndroidManifest.xml#L25-L27

Source: https://github.com/LSPosed/LSPosed/wiki/Module-Scope
